### ISSUE TITLE
[Create product GC] Sai chính tả

### ISSUE THREAD

**Issue by Ruby10291** [hungdq123/Giftvoucher-M2-Update#7]
http://prntscr.com/cme9fn
http://prntscr.com/cmeyna
http://prntscr.com/cnzxtd

**Comment by Ruby10291** [comment]
re-open vi:
1. 2 hinh anh dau e thay van nhu cu, chua dc sua
2. hinh anh thu 3: thi anh sua gi rui day. jo no con ko show message nay len nua

**Comment by hungdq123** [comment]
phải chạy lại module vì đó là label của attribute
